server:
  address: 0.0.0.0
  port: 8060
  # remember to set up nginx or other reverse proxy for sending these headers
  # without them OAuth2 process will fail with 'invalid_redirect_uri' errors
  remote_ip_header: X-Forwarded-For
  protocol_header: X-Forwarded-Proto

spring:
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 30000MB
  datasource:
    url: jdbc:mariadb://localhost:3306/admin_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDB102Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: changeit
    port: 2525
    username: changeit
    password: changeit
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: changeit
            client-secret: changeit
            scope:
              - email
              - profile
          facebook:
            client-id: changeit
            client-secret: changeit
  web:
    cors:
      mappings:
        baseOrigins:
          allowed-origins: http://localhost:4200
          allowed-methods: GET, POST, PUT, DELETE, OPTIONS
          max-age: 3600
          allowed-headers: Requestor-Type
          allow-credentials: true


assm:
  app:
    jwtSecret: Y26EJCVYYKML7YIPHLYEGJ29O9ABNWF7MLX71VTPXWEPKAN0LAPTMCC116D9K84OWV5TSVMKV5OTWVZMVKPRJCXOUWS53Z5L0WWTVZORS8Z747C77XX5JYLN


users:
  defaultAdminLogin: 1@example.com
  defaultAdminPass: 12345
  defaultAdminRoleName: superadmin
  defaultUserRoleName: user

log:
  entries: 100

mail:
  enabled: true
  locale: ru

# This url will be used in emails sent to client to redirect them to the frontend
frontend:
  location: http://localhost:8080/#

passwordRestoreToken:
  expireMillis: 1000000

features:
  oauthEnabled: true
  registrationEnabled: true