spring:
  datasource:
    url: jdbc:mysql://db:3306/admin_template_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: 12345

baseUrl: https://changeit.com